Vizew Solution-with-TestData-20190425/Vizew.WebUI/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vizew.WebUI.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Vizew Solution-with-TestData-20190425/Vizew.WebUI/Controllers/HomeController.cs
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vizew.WebUI.Models;

namespace Vizew.WebUI.Controllers
{
    [RoutePrefix("News")]
    public class HomeController : Controller
    {
        private VizewDbContext db = new VizewDbContext();

        public ActionResult Index()
        {
            
            var news = db.News.Where(n => n.IsPopular && n.DeletedDate == null)
                   .OrderByDescending(n => n.Id)
                   .Take(10)
                   .ToList();

            return View(news);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            //string id = Request.QueryString["id"];
            //if (string.IsNullOrWhiteSpace(id))
            //{
            //    id = Request.Form["id"];
            //}

            //string name = Request.Form["name"];
            //string email = Request.Form["email"];
            //string message = Request.Form["message"];



            ViewBag.Message = "Your application description page.";

            return View();
        }


        public ActionResult AcrchiveGrid()
        {
            return View();
        }

        public ActionResult AcrchiveList()
        {
            return View();
        }

        [Route("{category}/{title}-{id}")]
        [VizewExceptionFilter]
        public ActionResult SinglePost(int id)
        {
            var news = db.News.Find(id);
            //decimal a = 1 / decimal.Parse("0");
            //throw new HttpException((int)HttpStatusCode.BadRequest, "Xətalı müraciət!");
            return View(news);
        }
               
        public ActionResult VideoPost()
        {
            return View();
        }


        public ActionResult Typography()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Vizew Solution-with-TestData-20190425/Vizew.WebUI/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vizew.WebUI.Models;
using Vizew.WebUI.Models.Entity;

namespace Vizew.WebUI.Controllers
{
    public class InfoController : Controller
    {
        public ActionResult Index()
        {
            VizewDbContext db = new VizewDbContext();

            var info = db.Info.Where(n => n.IsRead == false)
                  .ToList();

            return View(info);
        }




        [HttpPost]
        public ActionResult Create(Info info)
        {
            VizewDbContext db = new VizewDbContext();

            if (ModelState.IsValid)
            {
                db.Info.Add(info);
                db.SaveChanges();
              
                return RedirectToAction("Index","Home");
            }

            return View(info);
            
        }
    }
}

Vizew Solution-with-TestData-20190425/Vizew.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Vizew Solution-with-TestData-20190425/Vizew.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="vizew-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Contact</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<section class="contact-area mb-80">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-7 col-lg-8">
                <div class="section-heading style-2">
                    <h4>Contact</h4>
                    <div class="line"></div>
                </div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                <div class="contact-form-area mt-50">
                    <form action="@Url.Action("Create","Info",routeValues:new { id=8})?id=15" method="post">
                        <div class="form-group">
                            <label for="name">Name*</label>
                            <input name="name" type="text" class="form-control" id="name">
                        </div>
                        <div class="form-group">
                            <label for="email">Email*</label>
                            <input name="email" type="email" class="form-control" id="email">
                        </div>
                        <div class="form-group">
                            <label for="message">Message*</label>
                            <textarea name="message" class="form-control" id="message" cols="30" rows="10"></textarea>
                        </div>
                        <button class="btn vizew-btn mt-30" type="submit">Send Now</button>
                    </form>
                </div>
            </div>
            <div class="col-12 col-md-5 col-lg-4">
                <div class="sidebar-area">
                    <div class="single-widget newsletter-widget mb-50">
                        <div class="section-heading style-2 mb-30">
                            <h4>Newsletter</h4>
                            <div class="line"></div>
                        </div>
                        <p>Subscribe our newsletter gor get notification about new updates, information discount, etc.</p>
                        <div class="newsletter-form">
                            <form action="#" method="post">
                                <input type="email" name="nl-email" class="form-control mb-15" id="emailnl" placeholder="Enter your email">
                                <button type="submit" class="btn vizew-btn w-100">Subscribe</button>
                            </form>
                        </div>
                    </div>
                    <div class="single-widget add-widget">
                        <a href="#"><img src="img/bg-img/add.png" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Vizew Solution-with-TestData-20190425/Vizew.WebUI/Views/Home/SinglePost.cshtml
@model Vizew.WebUI.Models.Entity.News
@{
    ViewBag.Title = "SinglePost";
}

<div class="vizew-breadcrumb">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Archives</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Reunification of migrant toddlers</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="vizew-pager-area">
    <div class="vizew-pager-prev">
        <p>PREVIOUS ARTICLE</p>
        <div class="single-feature-post video-post bg-img pager-article" style="background-image: url(img/bg-img/15.jpg);">
            <div class="post-content">
                <a href="#" class="post-cata cata-sm cata-success">Sports</a>
                <a href="video-post.html" class="post-title">Searching for the 'angel' who held me on Westminster Bridge</a>
                <div class="post-meta d-flex">
                    <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 18</a>
                    <a href="#"><i class="fa fa-eye" aria-hidden="true"></i> 32</a>
                    <a href="#"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> 24</a>
                </div>
            </div>
            <span class="video-duration">11.13</span>
        </div>
    </div>
    <div class="vizew-pager-next">
        <p>NEXT ARTICLE</p>
        <div class="single-feature-post video-post bg-img pager-article" style="background-image: url(img/bg-img/14.jpg);">
            <div class="post-content">
                <a href="#" class="post-cata cata-sm cata-business">Business</a>
                <a href="video-post.html" class="post-title">Reunification of migrant toddlers, parents should be completed Thursday</a>
                <div class="post-meta d-flex">
                    <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 25</a>
                    <a href="#"><i class="fa fa-eye" aria-hidden="true"></i> 25</a>
                    <a href="#"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> 25</a>
                </div>
            </div>
            <span class="video-duration">06.59</span>
        </div>
    </div>
</div>

<section class="post-details-area mb-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="post-details-thumb mb-50">
                    <img src="~/Template/media/@Model.MediaUrl" alt="">
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8 col-xl-7">
                <div class="post-details-content">
                    <div class="blog-content">
                        <div class="post-content mt-0">
                            <a href="#" class="post-cata cata-sm cata-danger">@Model.Category.Name</a>
                            <a href="single-post.html" class="post-title mb-2">@Model.Title</a>
                            <div class="d-flex justify-content-between mb-30">
                                <div class="post-meta d-flex align-items-center">
                                    <a href="#" class="post-author">By Jane</a>
                                    <i class="fa fa-circle" aria-hidden="true"></i>
                                    <a href="#" class="post-date">Sep 08, 2018</a>
                                </div>
                                <div class="post-meta d-flex">
                                    <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 32</a>
                                    <a href="#"><i class="fa fa-eye" aria-hidden="true"></i> 42</a>
                                    <a href="#"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> 7</a>
                                </div>
                            </div>
                        </div>
                        @Html.Raw(Model.Body)
                        
                        <div class="comment_area clearfix mb-50">
                            <div class="section-heading style-2">
                                <h4>Comment</h4>
                                <div class="line"></div>
                            </div>
                            <ul>
                                <li class="single_comment_area">
                                    <div class="comment-content d-flex">
                                        <div class="comment-author">
                                            <img src="~/Template/img/bg-img/31.jpg" alt="author">
                                        </div>
                                        <div class="comment-meta">
                                            <a href="#" class="comment-date">27 Aug 2019</a>
                                            <h6>Tomas Mandy</h6>
                                            <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius</p>
                                            <div class="d-flex align-items-center">
                                                <a href="#" class="like">like</a>
                                                <a href="#" class="reply">Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                    <ol class="children">
                                        <li class="single_comment_area">
                                            <div class="comment-content d-flex">
                                                <div class="comment-author">
                                                    <img src="~/Template/img/bg-img/32.jpg" alt="author">
                                                </div>
                                                <div class="comment-meta">
                                                    <a href="#" class="comment-date">27 Aug 2019</a>
                                                    <h6>Britney Millner</h6>
                                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius</p>
                                                    <div class="d-flex align-items-center">
                                                        <a href="#" class="like">like</a>
                                                        <a href="#" class="reply">Reply</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ol>
                                </li>
                                <li class="single_comment_area">
                                    <div class="comment-content d-flex">
                                        <div class="comment-author">
                                            <img src="~/Template/img/bg-img/33.jpg" alt="author">
                                        </div>
                                        <div class="comment-meta">
                                            <a href="#" class="comment-date">27 Aug 2019</a>
                                            <h6>Simon Downey</h6>
                                            <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius</p>
                                            <div class="d-flex align-items-center">
                                                <a href="#" class="like">like</a>
                                                <a href="#" class="reply">Reply</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="post-a-comment-area">
                            <div class="section-heading style-2">
                                <h4>Leave a reply</h4>
                                <div class="line"></div>
                            </div>
                            <div class="contact-form-area">
                                <form action="#" method="post">
                                    <div class="row">
                                        <div class="col-12 col-lg-6">
                                            <input type="text" class="form-control" id="name" placeholder="Your Name*">
                                        </div>
                                        <div class="col-12 col-lg-6">
                                            <input type="email" class="form-control" id="email" placeholder="Your Email*">
                                        </div>
                                        <div class="col-12">
<textarea name="message" class="form-control" id="message" placeholder="Message*"></textarea>
                                        </div>
                                        <div class="col-12">
                                            <button class="btn vizew-btn mt-30" type="submit">Submit Comment</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                <div class="sidebar-area">
                    <div class="single-widget share-post-widget mb-50">
                        <p>Share This Post</p>
                        <a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i> Facebook</a>
                        <a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i> Twitter</a>
                        <a href="#" class="google"><i class="fa fa-google" aria-hidden="true"></i> Google+</a>
                    </div>
                    <div class="single-widget p-0 author-widget">
                        <div class="p-4">
                            <img class="author-avatar" src="~/Template/img/bg-img/30.jpg" alt="">
                            <a href="#" class="author-name">Chris Hemsworth</a>
                            <div class="author-social-info">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                            </div>
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing</p>
                        </div>
                        <div class="authors--meta-data d-flex">
                            <p>Posted<span class="counter">80</span></p>
                            <p>Comments<span class="counter">230</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
